# These are really not much ways to support this project. It was a hobby after all. You can buy me a coffee, though. And, big companies out there... Like ProtonMail, if you would like to sponsor me, that would be a smart decision for you. I know I would if I were you. ;) 
buy_me_a_coffee: inboxkey

